config/routes.rb
Rails.application.routes.draw do
  resources :people
  get "welcome/say_hello" => "tosaysomething#say"
  get "welcome/" => "tosaysomething#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
#fix issue here, again
#fix issue by web
#fix issue here
class Event < ApplicationRecord
	validates_presence_of :name 
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		#@events = Event.all
		@events = Event.page(params[:page]).per(5)
	end

	def show
		@event = Event.find(params[:id])
		@page_title = @event.name
	end

	def edit
		if params[:id] == nil
			@event = Event.new
		else
			@event = Event.find(params[:id])
		end
	end	

	def update
		if params[:id] == nil
			@event = Event.new(event_params)
			if @event.save
				flash[:notice] = "event was successfully created	"
				redirect_to :action => :index
			end
		else
			@event = Event.find(params[:id])
			if @event.update(event_params)
				flash[:notice] = "event was successfully updated"
				redirect_to :action => :show, :id => @event.id
			end
		end

		if @event.errors.any?
			render :action => :edit
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		flash[:alert] = "event was successfully deleted"
		redirect_to :action => :index
	end	

	private

	def event_params
  		params.require(:event).permit(:name, :description)
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birth)
    end
end

app/controllers/tosaysomething_controller.rb
class TosaysomethingController < ApplicationController
	def say

	end

	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tosaysomething_helper.rb
module TosaysomethingHelper
end

app/views/events/destory.html.erb
destory

app/views/events/edit.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event.id } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

	<%if @event.id == nil%>
    	<%= f.submit "Create" %>
    <%end%>
    <%if @event.id != nil%>
    	<%= f.submit "Update" %>	
    <%end%>
<% end %>

<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
  <li>
 	  <%= event.name %>
  <%= link_to 'Show', :controller => 'events', :action => 'show', :id => event.id %>
  <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event.id %>
  <%= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event.id %>
  </li>
<% end %>
</ul>
<%=paginate @events %>
<%= link_to 'New Event', :controller => 'events', :action => 'edit' %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to Index', :controller => 'events', :action => 'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Event Application"%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p style="color: green"><%= flash[:notice] %></p>
	<p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :birth %>
    <%= f.datetime_select :birth %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birth %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @person.birth %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/tosaysomething/index.html.erb
this is index<br>
<%= Time.now %><br>

<%=link_to 'Hello!', welcome_say_hello_path %>

app/views/tosaysomething/say.html.erb
Hello World